# Generated by Django 3.0 on 2020-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Deadline', models.DateField(auto_now_add=True)),
                ('Days', models.CharField(max_length=200)),
            ],
        ),
    ]
